### PR TITLE
 Implemented: CPU usage of specific process #123

### PR DESCRIPTION
**Pull request by tobysmith568**
Created a new plugin which monitors the CPU usage of a single process.

I couldn't figure out how to set the order of the plugins in the Add Widget dialog so it currently sits about 2 thirds down the list on my machine - I think ideally it should sit directly beneath the plugin which monitors the total CPU usage

### CODE REVIEW

**Comment by tobysmith568** [comment]
Added a commit fixing a found typo

**Comment by tobysmith568** [comment]
Removed generated comments

**Comment by AlonAm** [comment]
Perfect implementation.
I appreciate elegant coding style, awesome work!

**Comment by AlonAm** [comment]
anystatus/support#123

**Comment by AlonAm** [comment]
@tobysmith568 there's an option to create a drop-down list of current processes, like in Windows Service plugin. We may want to add that later.

**Pull request merged**
