### PR TITLE
Simplified team city settings

### PR DESCRIPTION
**Pull request by SamuelEnglard**
Added support for filling in Build ID and Branch from URL

### CODE REVIEW

**Comment by AlonAm** [comment]
So now the Branch and BuildTypeId fields are not needed? can we remove'em?

I'd like to suggest creating a new version which will be called TeamCityBuild_v1 and hide current TeamCityBuild (browsable = false) to let users shift to the new version gradually without introducing breaking changes.
This way, we will be able to completely remove the Branch and BuildTypeId fields and maintain backward compatibility.

There's also a way to automatically upgrade plugins for users.

What's your opinion?

**Comment by SamuelEnglard** [comment]
I'm not sure they're not needed. A user could want to change them after initial setup for example.

**Comment by AlonAm** [comment]
I feel that having both URL and other fields together would compromise simplicity.
In case a user change the build-type-id, which one is correct? the URL or build-type-id?

Let's start simple, using only the URL address (in a new version of the plugin, I'll help with that).
If you'll feel that those fields are missing, we can always revive them later.

Notice that users prefer a simple setup, like in this [issue](https://github.com/AnyStatus/Support/issues/10).

In my experience using the Jenkins plugin, having just the URL is good enough, assuming it is simple to find that URL in TeamCity.

**Comment by SamuelEnglard** [comment]
Note that in the current system I remove everything but the host from the URL when input. 

As for confusing users, maybe move branch and build id to an "advanced" section that's hidden by default?

**Comment by AlonAm** [comment]
Trying to figure out how to fork the pull request into my computer, to fix the bug...

**Comment by AlonAm** [comment]
Dude, the PR in no longer relevant due to the breaking changes of v2.0
I will try to re-implement your changes further down the road.
Thank you for your contribution!

**Pull request closed without merging**
