### PR TITLE
AppVeyor - optionally trigger specific branch

### PR DESCRIPTION
**Pull request by mattmckinstry**
Optionally trigger a specific branch and check build status

### CODE REVIEW

**Comment by AlonAm** [comment]
Released in 1.5.24

Thank you!

**Comment by AlonAm** [comment]
@mattmckinstry  is this relevant only to triggering builds or monitoring the build status too?

**Comment by mattmckinstry** [comment]
Both, it allows you to trigger a build for a branch and also monitor the build status of the branch

https://www.appveyor.com/docs/api/projects-builds/#get-project-last-branch-build

**Comment by AlonAm** [comment]
That's awesome, thank you for your contribution!
If you'd  like to make further changes or add new plugins (AppVeyor deployment status for example),
I'm here to assist you :-)

**Pull request merged**
